#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
yum makecache fast

if [ ${DIB_DOCKER_INSTALL_VERSION:-latest} == "latest" ]; then
    yum install -y docker-ce
else
    yum install -y docker-ce-${DIB_DOCKER_INSTALL_VERSION}
fi
systemctl start docker
systemctl status docker
systemctl enable docker

